In [8]:
import multiprocessing as mp
import numpy as np

In [9]:
def multiply_row(args):
  row, B = args
  return np.dot(row, B)

In [10]:
def parallel_matrix_multiplication(A, B, no_of_workers=None):
    if (no_of_workers is None):
        no_of_workers = mp.cpu_count()
    with mp.Pool(processes=no_of_workers) as pool:
      result=pool.map(multiply_row, [(row, B) for row in A])

    return np.array(result)

In [11]:
if __name__ == "__main__":
  matrix1 = [[1, 2, 3], [4, 5, 6],[7,8,9]]
  matrix2 = [[9,8,7], [6,5,4], [3,2,1]]

  result = parallel_matrix_multiplication(matrix1, matrix2)
  print("Result AxB:\n", result)

Result AxB:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
